// Package apidocs Code generated by swaggo/swag. DO NOT EDIT
package apidocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/accounts/delete": {
            "post": {
                "description": "Permanently remove one shared account's key material from this client's storage. The Address field must match the stored account address as a safety confirmation. Irreversible.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Delete account",
                "parameters": [
                    {
                        "description": "Account to delete (with address confirmation)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.AccountDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/accounts/get": {
            "post": {
                "description": "Return metadata for a single locally stored account identified by network and index.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get account",
                "parameters": [
                    {
                        "description": "Account identifier",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.AccountGetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.AccountMeta"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/accounts/list": {
            "get": {
                "description": "List all locally stored accounts, optionally filtered by network.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List accounts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by network: eth or btc",
                        "name": "network",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.AccountsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "Verifies the EIP-191 signature over the nonce message and returns a JWT (valid 24h) on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login with a signed nonce",
                "parameters": [
                    {
                        "description": "Address, signature and nonce",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/nonce": {
            "post": {
                "description": "Returns a nonce and an EIP-191 message for the given ETH address. The client signs the message and submits it to /v1/auth/login.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Request a login nonce",
                "parameters": [
                    {
                        "description": "ETH address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.NonceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.NonceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/balance/check": {
            "post": {
                "description": "Check the current on-chain balance of an address and whether it meets the expected amount.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balance"
                ],
                "summary": "Check balance",
                "parameters": [
                    {
                        "description": "Balance check parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.BalanceCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.BalanceCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/balance/wait": {
            "post": {
                "description": "Poll the on-chain balance of an address until it reaches the expected amount or the timeout elapses.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "balance"
                ],
                "summary": "Wait for balance",
                "parameters": [
                    {
                        "description": "Balance wait parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.BalanceWaitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.BalanceWaitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/escrow": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits one party's pub/hash/sig for an escrow ID. When both parties' signatures validate, returns status \"complete\" with the counterparty signature; otherwise status \"pending\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "escrow"
                ],
                "summary": "Submit an escrow flower",
                "parameters": [
                    {
                        "description": "Escrow flower",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.EscrowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/exchanges/create": {
            "post": {
                "description": "Create an exchange entry. Addresses are optional and can be filled in later via /update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Create exchange (draft)",
                "parameters": [
                    {
                        "description": "Exchange addresses (optional)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/client.ExchangeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.Exchange"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/exchanges/delete": {
            "post": {
                "description": "Delete an exchange entry identified by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Delete exchange",
                "parameters": [
                    {
                        "description": "Exchange id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.ExchangeDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/exchanges/list": {
            "get": {
                "description": "Return all locally stored exchange entries (newest first).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "List exchanges",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.ExchangeListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/exchanges/update": {
            "post": {
                "description": "Update the addresses of an existing exchange identified by id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exchanges"
                ],
                "summary": "Update exchange",
                "parameters": [
                    {
                        "description": "Exchange id and addresses",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.ExchangeUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.Exchange"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/incomplete-signature/accept": {
            "post": {
                "description": "Run the accepting half of an MPC withdrawal signature and return the complete signature (ECDSA co-sign, or FROST co-sign).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incomplete-signature"
                ],
                "summary": "Accept incomplete signature",
                "parameters": [
                    {
                        "description": "Withdrawal signing parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.AcceptWithdrawalTxRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.AcceptWithdrawalTxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/incomplete-signature/send": {
            "post": {
                "description": "Run the initiating half of an MPC withdrawal signature (ECDSA incomplete signature send, or FROST round2/round3 exchange).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incomplete-signature"
                ],
                "summary": "Send incomplete signature",
                "parameters": [
                    {
                        "description": "Withdrawal signing parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.SendWithdrawalTxRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.SendWithdrawalTxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/keygen/ecdsa": {
            "post": {
                "description": "Run the local half of an ECDSA (CMP) 2-of-2 distributed key generation and presignature. Saves key material locally and returns the resulting address and public key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keygen"
                ],
                "summary": "ECDSA keygen",
                "parameters": [
                    {
                        "description": "Keygen parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.KeygenECDSARequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.KeygenECDSAResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/keygen/frost": {
            "post": {
                "description": "Run the local half of a FROST Taproot 2-of-2 distributed key generation. Saves key material locally and returns the resulting Bitcoin address and public key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "keygen"
                ],
                "summary": "FROST keygen",
                "parameters": [
                    {
                        "description": "Keygen parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.KeygenFROSTRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.KeygenFROSTResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mailbox/ack": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a message from the caller's inbox by ID. Only the recipient may ack a message. Returns 204 No Content on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Acknowledge a message",
                "parameters": [
                    {
                        "description": "Message ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.MailboxAckRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mailbox/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all undelivered (un-acked) messages addressed to the caller.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "List pending messages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.MailboxPendingResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mailbox/send": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a message to the other member of the given pair. The caller must be a member of the pair and the recipient must be the other member.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailbox"
                ],
                "summary": "Send a mailbox message",
                "parameters": [
                    {
                        "description": "Message to send",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.MailboxSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.MailboxSendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/pair/accept": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The partner accepts a pending pair by its ID. Idempotent: returns the pair if it is already accepted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pair"
                ],
                "summary": "Accept a pair",
                "parameters": [
                    {
                        "description": "Pair ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.PairAcceptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.PairAcceptResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/pair/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a pending pair request to another ETH address. Idempotent: returns the existing pair if present.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pair"
                ],
                "summary": "Create a pair",
                "parameters": [
                    {
                        "description": "Partner address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.PairCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.PairCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/pair/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes a pair entirely (both participants lose it). Only a member of the pair may delete it. Idempotent: returns success if the pair is already gone.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pair"
                ],
                "summary": "Delete a pair",
                "parameters": [
                    {
                        "description": "Pair ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.PairAcceptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/pair/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all pairs involving the caller, split into incoming (caller is partner) and outgoing (caller is initiator).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pair"
                ],
                "summary": "List pending pairs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.PairPendingResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/session/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The initiator calls this to cancel. ok=true means cancelled; ok=false means the partner already claimed (too late to cancel).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Cancel a keygen session",
                "parameters": [
                    {
                        "description": "Session ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/session/claim": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The partner calls this before running its keygen half. ok=true means proceed; ok=false means the initiator already cancelled.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Claim a keygen session",
                "parameters": [
                    {
                        "description": "Session ID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.SessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.SessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/timebox": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns whether a stored signature exists and is valid for the given pub/hash. Once the timebox delay has elapsed, includes the base64 signature. Only members of the bound pair may read.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timebox"
                ],
                "summary": "Get a timebox signature",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public key (hex)",
                        "name": "pub",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message hash (hex, 32 bytes)",
                        "name": "hash",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stores a validated signature bound to a pair. The signature becomes retrievable via GET after the timebox delay (1 hour). Only members of the pair may POST.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timebox"
                ],
                "summary": "Store a timebox signature",
                "parameters": [
                    {
                        "description": "Timebox entry",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.TimeboxPostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tx/hash": {
            "post": {
                "description": "Build an unsigned transaction for the given network and return the hash to be signed (and raw tx data where available).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tx"
                ],
                "summary": "Create transaction hash",
                "parameters": [
                    {
                        "description": "Transaction parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.TxHashRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.TxHashResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tx/send": {
            "post": {
                "description": "Apply a signature to a transaction and broadcast it to the given network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tx"
                ],
                "summary": "Send transaction",
                "parameters": [
                    {
                        "description": "Signed transaction parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/client.SendTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/client.SendTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/client.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "client.AcceptWithdrawalTxRequest": {
            "type": "object",
            "properties": {
                "alg": {
                    "type": "string"
                },
                "another_id": {
                    "type": "string"
                },
                "escrow_address": {
                    "type": "string"
                },
                "hash_tx": {
                    "description": "HashTx обязателен для FROST: протокол сам не пересылает хеш —\nобе стороны должны знать, что подписывают, заранее (через mailbox/UI).\nДля ECDSA не используется (хеш приходит в payload incomplete-signature).",
                    "type": "string"
                },
                "my_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "client.AcceptWithdrawalTxResponse": {
            "type": "object",
            "properties": {
                "complete_signature": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "client.AccountDeleteRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "confirmation",
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                }
            }
        },
        "client.AccountGetRequest": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                }
            }
        },
        "client.AccountMeta": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                },
                "pair_my_id": {
                    "type": "string"
                },
                "pair_other": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "client.AccountsListResponse": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.AccountMeta"
                    }
                }
            }
        },
        "client.BalanceCheckRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "expected": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                }
            }
        },
        "client.BalanceCheckResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "integer"
                },
                "expected": {
                    "type": "integer"
                },
                "is_sufficient": {
                    "type": "boolean"
                },
                "network": {
                    "type": "string"
                }
            }
        },
        "client.BalanceWaitRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "expected": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                },
                "timeout_sec": {
                    "type": "integer"
                }
            }
        },
        "client.BalanceWaitResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "integer"
                },
                "expected": {
                    "type": "integer"
                },
                "is_sufficient": {
                    "type": "boolean"
                },
                "network": {
                    "type": "string"
                },
                "timed_out": {
                    "type": "boolean"
                }
            }
        },
        "client.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "client.Exchange": {
            "type": "object",
            "properties": {
                "address_a": {
                    "type": "string"
                },
                "address_b": {
                    "type": "string"
                },
                "created_at": {
                    "description": "unix ms",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "client.ExchangeCreateRequest": {
            "type": "object",
            "properties": {
                "address_a": {
                    "type": "string"
                },
                "address_b": {
                    "type": "string"
                }
            }
        },
        "client.ExchangeDeleteRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "client.ExchangeListResponse": {
            "type": "object",
            "properties": {
                "exchanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/client.Exchange"
                    }
                }
            }
        },
        "client.ExchangeUpdateRequest": {
            "type": "object",
            "properties": {
                "address_a": {
                    "type": "string"
                },
                "address_b": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "client.KeygenECDSARequest": {
            "type": "object",
            "properties": {
                "another_id": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "my_id": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "client.KeygenECDSAResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "client.KeygenFROSTRequest": {
            "type": "object",
            "properties": {
                "another_id": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "my_id": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "client.KeygenFROSTResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "public_key": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                }
            }
        },
        "client.SendTransactionRequest": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "from": {
                    "type": "string"
                },
                "gas_limit": {
                    "type": "string"
                },
                "gas_price": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "node_url": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "client.SendTransactionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "client.SendWithdrawalTxRequest": {
            "type": "object",
            "properties": {
                "alg": {
                    "type": "string"
                },
                "another_id": {
                    "type": "string"
                },
                "escrow_address": {
                    "type": "string"
                },
                "hash_tx": {
                    "type": "string"
                },
                "my_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "client.SendWithdrawalTxResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "client.TxHashRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "chain_id": {
                    "type": "integer"
                },
                "from": {
                    "type": "string"
                },
                "gas_limit": {
                    "type": "integer"
                },
                "network": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "client.TxHashResponse": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "tx_data": {
                    "type": "string"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.EscrowRequest": {
            "type": "object",
            "properties": {
                "alg": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pub": {
                    "type": "string"
                },
                "sig": {
                    "type": "string"
                }
            }
        },
        "server.LoginRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "server.LoginResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "server.MailboxAckRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "server.MailboxPendingResponse": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.Message"
                    }
                }
            }
        },
        "server.MailboxSendRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "pair_id": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "server.MailboxSendResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "server.Message": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "integer"
                },
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pair_id": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "description": "\"keygen_request\", \"keygen_accept\", etc.",
                    "type": "string"
                }
            }
        },
        "server.NonceRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "server.NonceResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                }
            }
        },
        "server.Pair": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "initiator": {
                    "type": "string"
                },
                "partner": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "server.PairAcceptRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "server.PairAcceptResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "initiator": {
                    "type": "string"
                },
                "partner": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "server.PairCreateRequest": {
            "type": "object",
            "properties": {
                "partner": {
                    "type": "string"
                }
            }
        },
        "server.PairCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "initiator": {
                    "type": "string"
                },
                "partner": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "server.PairPendingResponse": {
            "type": "object",
            "properties": {
                "incoming": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.Pair"
                    }
                },
                "outgoing": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/server.Pair"
                    }
                }
            }
        },
        "server.SessionRequest": {
            "type": "object",
            "properties": {
                "session_id": {
                    "type": "string"
                }
            }
        },
        "server.SessionResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "server.TimeboxPostRequest": {
            "type": "object",
            "properties": {
                "alg": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "pair_id": {
                    "description": "обязателен: ограничивает, кто может POST/GET",
                    "type": "string"
                },
                "pub": {
                    "type": "string"
                },
                "sig": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT obtained from /v1/auth/login, sent as \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Signature Escrow API",
	Description:      "MPC 2-of-2 signature escrow wallet. Host (server) endpoints\nhandle auth, pairing, mailbox, keygen-session arbitration,\nescrow and timebox. Local (client) endpoints handle keygen,\naccounts, exchanges, balance, transactions and withdrawals.\nServer endpoints under /v1 (except /auth) require a Bearer JWT.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
